import Lake

open Lake DSL

package albertAlgebra where
  srcDir := "."

require mathlib from git
  "https://github.com/leanprover-community/mathlib4" @ "v4.26.0"

@[default_target]
lean_lib AlbertAlgebra where
  roots := #[
    `AlbertAlgebra,
    `AlbertAlgebraStatement,
    `AlbertAlgebraVerification,
    `Verification.Axioms
  ]

/-- Non-default target for the challenge generated by the comparator workflow. -/
lean_lib ComparatorChallenge where
  roots := #[`Challenge]
